import React from 'react'
import { render, screen } from '@testing-library/react'
import '@testing-library/jest-dom'
import PrintHeaderMetadata from '../Components/PrintHeaderMetadata'

describe('PrintHeaderMetadata', () => {
  describe('Basic Rendering', () => {
    it('renders with default title', () => {
      const { container } = render(<PrintHeaderMetadata />)
      const header = container.querySelector('.print-header-title')
      expect(header).toHaveTextContent('Dashboard Analytics Report')
    })

    it('renders with custom title', () => {
      const { container } = render(
        <PrintHeaderMetadata title="Custom Analytics Report" />
      )
      const header = container.querySelector('.print-header-title')
      expect(header).toHaveTextContent('Custom Analytics Report')
    })

    it('includes generation date', () => {
      const { container } = render(<PrintHeaderMetadata />)
      const subtitle = container.querySelector('.print-header-subtitle')
      expect(subtitle).toHaveTextContent('Generated:')
    })

    it('includes generated by user when provided', () => {
      const { container } = render(
        <PrintHeaderMetadata generatedBy="John Doe" />
      )
      const subtitle = container.querySelector('.print-header-subtitle')
      expect(subtitle).toHaveTextContent('By: John Doe')
    })
  })

  describe('Filter Display', () => {
    it('shows "No filters applied" when no filters provided', () => {
      const { container } = render(<PrintHeaderMetadata filters={{}} />)
      const filterInfo = container.querySelector('.print-filter-value')
      expect(filterInfo).toHaveTextContent('No filters applied')
    })

    it('displays date range filter', () => {
      const filters = {
        dateRange: {
          start: '2024-01-01',
          end: '2024-12-31'
        }
      }
      const { container } = render(<PrintHeaderMetadata filters={filters} />)
      const filterInfo = container.querySelector('.print-filter-value')
      expect(filterInfo).toHaveTextContent('Date: 2024-01-01 to 2024-12-31')
    })

    it('displays categories filter', () => {
      const filters = {
        categories: ['Sales', 'Marketing', 'Support']
      }
      const { container } = render(<PrintHeaderMetadata filters={filters} />)
      const filterInfo = container.querySelector('.print-filter-value')
      expect(filterInfo).toHaveTextContent('Categories: Sales, Marketing, Support')
    })

    it('displays status filter', () => {
      const filters = {
        status: 'Active'
      }
      const { container } = render(<PrintHeaderMetadata filters={filters} />)
      const filterInfo = container.querySelector('.print-filter-value')
      expect(filterInfo).toHaveTextContent('Status: Active')
    })

    it('displays region filter', () => {
      const filters = {
        region: 'North America'
      }
      const { container } = render(<PrintHeaderMetadata filters={filters} />)
      const filterInfo = container.querySelector('.print-filter-value')
      expect(filterInfo).toHaveTextContent('Region: North America')
    })

    it('displays multiple filters separated by bullets', () => {
      const filters = {
        dateRange: {
          start: '2024-01-01',
          end: '2024-12-31'
        },
        categories: ['Sales', 'Marketing'],
        status: 'Active'
      }
      const { container } = render(<PrintHeaderMetadata filters={filters} />)
      const filterInfo = container.querySelector('.print-filter-value')
      expect(filterInfo).toHaveTextContent('Date: 2024-01-01 to 2024-12-31')
      expect(filterInfo).toHaveTextContent('Categories: Sales, Marketing')
      expect(filterInfo).toHaveTextContent('Status: Active')
      expect(filterInfo).toHaveTextContent('•')
    })

    it('handles custom filter properties', () => {
      const filters = {
        customField: 'Custom Value'
      }
      const { container } = render(<PrintHeaderMetadata filters={filters} />)
      const filterInfo = container.querySelector('.print-filter-value')
      expect(filterInfo).toHaveTextContent('Custom Field: Custom Value')
    })

    it('handles array custom filters', () => {
      const filters = {
        tags: ['urgent', 'important']
      }
      const { container } = render(<PrintHeaderMetadata filters={filters} />)
      const filterInfo = container.querySelector('.print-filter-value')
      expect(filterInfo).toHaveTextContent('Tags: urgent, important')
    })
  })

  describe('Page Numbers', () => {
    it('includes footer when includePageNumbers is true', () => {
      const { container } = render(
        <PrintHeaderMetadata includePageNumbers={true} />
      )
      const footer = container.querySelector('.print-footer')
      expect(footer).toBeInTheDocument()
    })

    it('excludes footer when includePageNumbers is false', () => {
      const { container } = render(
        <PrintHeaderMetadata includePageNumbers={false} />
      )
      const footer = container.querySelector('.print-footer')
      expect(footer).not.toBeInTheDocument()
    })

    it('includes page numbers by default', () => {
      const { container } = render(<PrintHeaderMetadata />)
      const footer = container.querySelector('.print-footer')
      expect(footer).toBeInTheDocument()
    })
  })

  describe('Print-Only Visibility', () => {
    it('has print-only class on header', () => {
      const { container } = render(<PrintHeaderMetadata />)
      const header = container.querySelector('.print-header')
      expect(header).toHaveClass('print-only')
    })

    it('has print-only class on footer', () => {
      const { container } = render(<PrintHeaderMetadata />)
      const footer = container.querySelector('.print-footer')
      expect(footer).toHaveClass('print-only')
    })

    it('has display none inline style for screen', () => {
      const { container } = render(<PrintHeaderMetadata />)
      const header = container.querySelector('.print-header')
      expect(header).toHaveStyle({ display: 'none' })
    })
  })

  describe('Edge Cases', () => {
    it('handles null filters gracefully', () => {
      const { container } = render(<PrintHeaderMetadata filters={null} />)
      const filterInfo = container.querySelector('.print-filter-value')
      expect(filterInfo).toHaveTextContent('No filters applied')
    })

    it('handles undefined filters gracefully', () => {
      const { container } = render(<PrintHeaderMetadata />)
      // Should not crash and should render header
      const header = container.querySelector('.print-header-title')
      expect(header).toBeInTheDocument()
    })

    it('handles empty string title', () => {
      const { container } = render(<PrintHeaderMetadata title="" />)
      const header = container.querySelector('.print-header-title')
      expect(header).toHaveTextContent('')
    })

    it('handles date range with only start date', () => {
      const filters = {
        dateRange: {
          start: '2024-01-01'
        }
      }
      const { container } = render(<PrintHeaderMetadata filters={filters} />)
      const filterInfo = container.querySelector('.print-filter-value')
      expect(filterInfo).toHaveTextContent('Date: From 2024-01-01')
    })

    it('handles date range with only end date', () => {
      const filters = {
        dateRange: {
          end: '2024-12-31'
        }
      }
      const { container } = render(<PrintHeaderMetadata filters={filters} />)
      const filterInfo = container.querySelector('.print-filter-value')
      expect(filterInfo).toHaveTextContent('Date: Until 2024-12-31')
    })

    it('handles empty categories array', () => {
      const filters = {
        categories: []
      }
      const { container } = render(<PrintHeaderMetadata filters={filters} />)
      const filterInfo = container.querySelector('.print-filter-value')
      expect(filterInfo).toHaveTextContent('No filters applied')
    })
  })

  describe('Requirement Validation', () => {
    it('validates Requirement 5.5: includes page numbers', () => {
      const { container } = render(<PrintHeaderMetadata />)
      const footer = container.querySelector('.print-footer')
      expect(footer).toBeInTheDocument()
      // Page numbers are added via CSS ::after pseudo-element
    })

    it('validates Requirement 5.5: includes generation date', () => {
      const { container } = render(<PrintHeaderMetadata />)
      const subtitle = container.querySelector('.print-header-subtitle')
      expect(subtitle).toHaveTextContent('Generated:')
    })

    it('validates Requirement 4.4: preserves filter criteria', () => {
      const filters = {
        dateRange: { start: '2024-01-01', end: '2024-12-31' },
        categories: ['Sales'],
        status: 'Active'
      }
      const { container } = render(<PrintHeaderMetadata filters={filters} />)
      const filterInfo = container.querySelector('.print-filter-value')
      
      // All filter criteria should be present
      expect(filterInfo).toHaveTextContent('Date: 2024-01-01 to 2024-12-31')
      expect(filterInfo).toHaveTextContent('Categories: Sales')
      expect(filterInfo).toHaveTextContent('Status: Active')
    })
  })
})
